// Generated by CoffeeScript 1.9.3
window.onload = function() {
  var game;

  game = new Phaser.Game(480, 854, Phaser.AUTO, 'lifesim');

  game.state.add('boot', require('./states/boot'));
  game.state.add('gameover', require('./states/gameover'));
  game.state.add('menu', require('./states/menu'));
  game.state.add('play', require('./states/play'));
  game.state.add('preload', require('./states/preload'));

  return game.state.start('boot');
};

