// Generated by CoffeeScript 1.9.3
(function() {
  var Boot;

  Boot = function() {};

  Boot.prototype = {
    preload: function() {
      this.load.image('preloader', 'assets/preloader.gif');
    },
    create: function() {
      this.game.input.maxPointers = 1;
      this.game.state.start('preload');
    }
  };

  module.exports = Boot;

}).call(this);
